apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  mongo-user: bW9uZ28tdXNlcg==
  mongo-password: bW9uZ28tcGFzc3dvcmQ=